#!/usr/bin/python

from sympy import diff, Symbol, latex, Matrix


def optimization(function, x1, x2):
	firstx1 = diff(function, x1)
	firstx2 = diff(function, x2)

	secondx1x1 = diff(function, x1, x1)
	secondx1x2 = diff(function, x1, x2)
	secondx2x1 = diff(function, x2, x1)
	secondx2x2 = diff(function, x2, x2)

	print latex(function)
	print latex(firstx1)
	print latex(firstx2)

	print "\n Hessian elements:\n\n"
	print latex(secondx1x1) +"\t" + latex(secondx1x2)
	print latex(secondx2x1) + "\t"+latex(secondx2x2)

def matrix():
	a = Symbol('a')
	M = Matrix([a, 1, 1],[3, 2, 1],[2, 2, 3])
	print M

def main():
	x1 = Symbol('x1')
	x2 = Symbol('x2')

	function1 = 2*x1**2 - x1*x2 + (x2**2)/2 -3*x1 + 3.5
	function2 = (-3*(x1**2))/2 + x1*x2 - (x2**2)/2 + 2*x1 - 1
	function3 = x1**2 + 8*x1*x2 + (x2**2)/2 - 10*x1 -9*x2 +9/2	
	
	optimization(function3, x1,x2)

	matrix()

main()
